### PR TITLE
upgrade instruction to keptn full installation

### PR DESCRIPTION
**Pull request by jetzlstorfer**
- upgrade version
- adding new maintainer
- upgrading instructions to support full keptn installation

### CODE REVIEW

**Comment by saiyam1814** [comment]
@jetzlstorfer from the contributing guide 
"We envisage that install.sh script usage should be rare and we will be strictly monitoring what is in them, and NO downloading of external resources will be acceptable here (no curl https://... | sudo sh sort of functionality)"

**Comment by jetzlstorfer** [comment]
Keptn can only be installed via the CLI or via `helm`. would the later be an option or is this not available in the installer image?

**Comment by saiyam1814** [comment]
k3s supports helm3 CRD so you can have a yaml and have that installed. I would actually prefer this option!
Example 
```
apiVersion: v1
kind: Namespace
metadata:
  name: kubenav
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kubenav
  namespace: kube-system
spec:
  chart: kubenav
  targetNamespace: kubenav
  repo: https://kubenav.github.io/helm-repository
```

**Comment by jetzlstorfer** [comment]
I'll take a look at this.
nevertheless, we would need a combination via the helm chart and the script. the script configures Istio and therefore we need it anyway to remove the burden to execute some post-installation scripts by the user.

**Comment by jetzlstorfer** [comment]
Working on it but Keptn installer prevents it from being installed on Kubernetes 1.20+ as it is currently only tested for <= 1.19.
Will either need to resolve this within Keptn installation or find a way to set Kubernetes version in Civo.

**Comment by saiyam1814** [comment]
Hi @jetzlstorfer  right now we do not have multiple version for K3s, it's 1.20

**Comment by jetzlstorfer** [comment]
Thanks @saiyam1814 - I'll put this on hold for a moment as we need to upgrade our installer first.

**Comment by saiyam1814** [comment]
@jetzlstorfer would love to try Keptn with Civo Kubernetes from the Marketplace :)

**Comment by jetzlstorfer** [comment]
@saiyam1814 me too! 
I believe the Keptn full installation might need some tweaks on our end, but what shouldn't be a problem is to upgrade the existing installation for the latest version of Keptn. Let me have a look

**Comment by saiyam1814** [comment]
@jetzlstorfer we can close this one ?

**Comment by saiyam1814** [comment]
@jetzlstorfer we can close this one  right ?

**Comment by saiyam1814** [comment]
Closing this as we already updated with another PR

**Pull request closed without merging**
