### PR TITLE
Installing Keptn On Civo’s K3s Cluster

### PR DESCRIPTION
**Pull request by sangam14**
@andyjeffries  @saiyam1814  few days back tried keptn with k3s cluster . good to see new CI / CD tool in marketplace !

### CODE REVIEW

**Comment by saiyam1814** [comment]
Thanks for the PR @sangam14 , but there has to be a file named logo.png with the logo of the application , currently I see svg file, kindly remove that and create logo.png

**Comment by saiyam1814** [comment]
@sangam14 can you fix this ? 
keptn/logo.png is wider than 512px
keptn/logo.png is larger than 20KB

**Review by sangam14 — COMMENTED** [review]
@saiyam1814  added logo.png

**Comment by saiyam1814** [comment]
Also Can you Add little info about how this tool will help the community ? 
Rest lgtm

**Comment by sangam14** [comment]
> Also Can you Add little info about how this tool will help the community ?
> Rest lgtm. 
in short. 
Keptn is solves problems around continuous delivery with quality gates and automated operations for cloud native application .for more details https://keptn.sh/ .

**Comment by andyjeffries** [comment]
Maybe you’d be able/willing to write a learn guide on this tool, why it’s cool, how you use it etc? Kai from Civo can help with the process and provide editorial polish. Or maybe there’s a good page (aside from just - here’s their site) that we can link to and promote when it goes live on Civo.

**Comment by sangam14** [comment]
sure @andyjeffries ! sharing blog with @saiyam1814 for review ! also i will take help from @kaihoffman ! Thanks !

**Comment by saiyam1814** [comment]
Yes, @andyjeffries  I am going through the blog and will send to Kai as well. BTW Sangam is a good friend of mine

**Pull request merged**
