### PR TITLE
(add)litmuschaos: add litmuschaos to the civo K8s marketplace

### PR DESCRIPTION
**Pull request by ksatchit**
Signed-off-by: ksatchit <karthik.s@mayadata.io>

Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [ ] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

If your pull request concerns an existing Marketplace application, please make sure you have:

* [ ] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [ ] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [ ] Tested that the application works with the proposed updates applied (including a screenshot)

### CODE REVIEW

**Comment by ksatchit** [comment]
This is a WIP PR!

**Comment by saiyam1814** [comment]
@ksatchit is the post_install complete, ready to merge?

**Comment by saiyam1814** [comment]
no hurries

**Comment by ksatchit** [comment]
Hi @saiyam1814 !! We are good to go 👍

**Comment by saiyam1814** [comment]
Hi, @ksatchit have you seen how the post_install looks like in the civo dashboard after installing the app from the marketplace? 
Can we move the section where you are creating the Sa and instead point to the docs there? or to the blog that I already wrote? 
After installing this we will have the CRD's and then it's up to the user to install whatever experiment from chaos hub so this will massively reduce the post-install and will look good as well. Your thoughts?

**Comment by ksatchit** [comment]
Makes sense @saiyam1814 - will update it to point blog/docs post the install verification steps.

**Comment by saiyam1814** [comment]
LGTM

**Pull request merged**
