### PR TITLE
Upgrading Dapr to version 1.13.2

### PR DESCRIPTION
**Pull request by salaboy**
Keeping Dapr Release updated to stable latest

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?
* [x] Have you included the specific version of the application to be installed?

If your pull request concerns an existing Marketplace application, please make sure you have:

* [x] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [x] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [ ] Tested that the application works with the proposed updates applied (including a screenshot).
* [x] Updated the version number of the app if that has changed.

### CODE REVIEW

**Comment by olblak** [comment]
@salaboy If you are interested to automate this version bump automatically, you could add an update policy for Dapr in the directory  [.github/updatecli/updatecli.d](https://github.com/civo/kubernetes-marketplace/tree/master/.github/updatecli/updatecli.d)

It would open a pullrequest like this [one](https://github.com/civo/kubernetes-marketplace/pull/714)

You could take some inspiration from the Rancher [one](https://github.com/civo/kubernetes-marketplace/blob/master/.github/updatecli/updatecli.d/rancher.yaml) which seems to be the closest one.

Underneath there is an GitHub action [workflow](https://github.com/civo/kubernetes-marketplace/blob/master/.github/workflows/updatecli.yml) running [Updatecli](https://github.com/updatecli/updatecli) every hours.

**Comment by salaboy** [comment]
@olblak that is awesome.. i didn't knew that existed.. so I will do that for the next one.

**Comment by olblak** [comment]
> @olblak that is awesome.. i didn't knew that existed.. so I will do that for the next one.

Thanks

Disclaimer, I am not affiliated with CIVO :) but the founder of the Updatecli project.
I was interested to automate chart updates for projects I am involved with.

Also Updatecli is a standalone command line tool so you can test yourself as explained on [.github/updatecli/README.md](https://github.com/civo/kubernetes-marketplace/tree/master/.github/updatecli/README.md)

**Comment by saiyam1814** [comment]
> > @olblak that is awesome.. i didn't knew that existed.. so I will do that for the next one.
> 
> Thanks
> 
> Disclaimer, I am not affiliated with CIVO :) but the founder of the Updatecli project. I was interested to automate chart updates for projects I am involved with.
> 
> Also Updatecli is a standalone command line tool so you can test yourself as explained on [.github/updatecli/README.md](https://github.com/civo/kubernetes-marketplace/tree/master/.github/updatecli/README.md)

Thank you for this!

**Review by saiyam1814 — APPROVED** [review]

**Pull request merged**
