### PR TITLE
Adding kube-hunter tool

### PR DESCRIPTION
**Pull request by milindchawre**
Adding kube-hunter tool.

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

**Screenshot**
image

### CODE REVIEW

**Comment by milindchawre** [comment]
ping @saiyam1814

**Comment by saiyam1814** [comment]
@milindchawre this runs only once after we install it right?

**Comment by milindchawre** [comment]
yes

**Comment by saiyam1814** [comment]
Can we have a cronjob mentioned in the post-install if someone wants to test on daily basis?

**Comment by milindchawre** [comment]
Done.

**Comment by saiyam1814** [comment]
lgtm

**Pull request merged**
