### PR TITLE
upgrade prometheus-operator to new community repo #76

### PR DESCRIPTION
**Pull request by srinivasraja54**
Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

This is to fix the issue: https://github.com/civo/kubernetes-marketplace/issues/76

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [Y] Have you followed the guidelines in our Contributing document in setting up the application? 
* [Y] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [Y] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [Y] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

If your pull request concerns an existing Marketplace application, please make sure you have:

* [Y] Notified the Maintainer of the application in this pull request so that they are aware of your proposal. @puck
* [Y ] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc). 

* [Y ] Tested that the application works with the proposed updates applied (including a screenshot)
result

image

### CODE REVIEW

**Comment by saiyam1814** [comment]
@srinivasraja54 this is helm 3 right ?

**Comment by srinivasraja54** [comment]
yeah. I tried in helm3 in my local. But updated the install.sh according to existing syntax i.e helm2

**Comment by saiyam1814** [comment]
So if its helm3 then only way to use is as previous 
```
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-operator
  namespace: kube-system
spec:
  chart: stable/prometheus-operator
  version: 8.7.0
  targetNamespace: monitoring
```

else for what you have committed try with helm2 and attach the screenshot

**Comment by srinivasraja54** [comment]
image
image


With helm2 I have deployed successfully.  when I tried with app.yaml(helm3) initially, charts from other repos like prometheus-community were not downloading.

**Comment by saiyam1814** [comment]
ok I need to try it out with helm 2 if that works then I will merge till then will be leaving the PR opened

**Comment by saiyam1814** [comment]
on trying it has issues with the commands provided in the PR so once you fix it just comment and tag me

**Comment by srinivasraja54** [comment]
Hi @saiyam1814 

I tried on a fresh civo cluster. I ran into below issue while installing the operatory through helm2

> `Error: namespaces "monitoring" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "monitoring"
> `

I patched helm-deploy with below command

`kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'`

Then I faced another error related to operator installation

> [root@srinu ~]# helm install   --name prometheus-operator   --namespace monitoring   --version 9.4.4   prometheus-community/kube-prometheus-stack
> E1002 03:47:36.632936    1740 portforward.go:400] an error occurred forwarding 41857 -> 44134: error forwarding port 44134 to pod 6a6666993eeac480dbe58fed174ab3fd218176ec54cec8f7de42ddcdcb84adf5, uid : network namespace for sandbox "6a6666993eeac480dbe58fed174ab3fd218176ec54cec8f7de42ddcdcb84adf5" is closed


Then I created a cluster role as below

```
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
clusterrolebinding.rbac.authorization.k8s.io/tiller-cluster-rule created
```
With same command I'm able to deploy. There are few issues with tiller & its rolebinding. If you are facing the same issue, I'll add the two commands to install.sh. rest of the commands are same. Helm init~ commands are not part of install.sh for other marketplace apps(for eg:https://github.com/civo/kubernetes-marketplace/blob/master/cert-manager/install.sh) So these privileges would be part of civo helm I suppose. Let me know your view. I will include above commands accordingly

image

**Comment by saiyam1814** [comment]
with the k3s helm 3 CRD you were not able to deploy ?

**Comment by saiyam1814** [comment]
@srinivasraja54 can you rework this update? we have helm3 in place now!!

**Comment by srinivasraja54** [comment]
@saiyam1814 sure sairam I will work on this, this weekend. Thanks for the update

**Comment by saiyam1814** [comment]
Thanks, @srinivasraja54 let me know if you face any issues!

**Comment by srinivasraja54** [comment]
I will close this during this weekend. Sorry for the delay

**Comment by saiyam1814** [comment]
@srinivasraja54 any updates on this ?

**Comment by saiyam1814** [comment]
@srinivasraja54 would you need any help on this?

**Comment by srinivasraja54** [comment]
@saiyam1814 I had issues with login due to old cluster on civo cloud. With new one, I'm able to login and tried Prometheus-operator installation. I've  updated the commits. Attached screenshots. Please check and let me know

**Comment by saiyam1814** [comment]
LGTM

**Pull request merged**
