### PR TITLE
Update k8s dashboard

### PR DESCRIPTION
**Pull request by Ludea**
Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x ] Have you followed the guidelines in our Contributing document in setting up the application?
* [ ] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [ ] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x ] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

If your pull request concerns an existing Marketplace application, please make sure you have:

* [ ] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [ x] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [ ] Tested that the application works with the proposed updates applied (including a screenshot)

Update k8s dashboard to v2.0 stable version
cc @morganlaneap

### CODE REVIEW

**Comment by morganlaneap** [comment]
Has this been tested on a cluster? Aside from that looks good!

**Comment by Ludea** [comment]
k8s-dashboard

**Comment by morganlaneap** [comment]
Great. I'd post this in the Slack channel and one of the guys will get to it :)

**Comment by andyjeffries** [comment]
Thank you :-) Merging now...

**Pull request merged**
