### PR TITLE
fix: Fix Tekton installation

### PR DESCRIPTION
**Pull request by SergK**
There is an issue by applying single app.yaml file and we fail to create CRDs and CRs in the same apply request [1]. This patch changes the approach on how to install tekton, first by creating CRD and then apply the rest of the Tekton Stack with CRs

[1]. https://github.com/kubernetes/kubectl/issues/1179

Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [ ] Have you followed the guidelines in our Contributing document in setting up the application?
* [ ] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [ ] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [ ] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?
* [ ] Have you included the specific version of the application to be installed?

If your pull request concerns an existing Marketplace application, please make sure you have:

* [x] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [x] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [x] Tested that the application works with the proposed updates applied (including a screenshot).
* [x] Updated the version number of the app if that has changed.

### CODE REVIEW

**Comment by SergK** [comment]
Here is installation check:
image

**Comment by SergK** [comment]
Hello @ssmiller25, could you please review the patch?

**Comment by ssmiller25** [comment]
@SergK Thanks for the PR!  Excellent bug you found - something that probably donesn't always appear in testing.  Out of curiosity, why did you only put one CRD in the install.sh script?  There are 16 in the app.yaml, and I assume all of them could potentially suffer the same issue? 

Again, great find.  Just hoping to make sure this fully resolves any future issues.

**Comment by SergK** [comment]
@ssmiller25 The installation process creates **only one type** of custom resource (CR), which is the "**clusterinterceptors**" CR.
Therefore, we are only pre-creating CRD **clusterinterceptors** initially, and there's no need to pre-create other CRDs. Another goal is to keep everything working with the original Makefile (upstream updates), simplifying further manual updates so that the Make build will produce the expected results from upstream.

**Comment by ssmiller25** [comment]
@SergK Gotcha!  Thanks for the clarification!  I should have looked to see actual CRs that were created during the install.  In that case, everything LGTM!

**Comment by ssmiller25** [comment]
@saiyam1814 Everything looks good from my perspective, but I’m unable to submit an approval on GitHub.

**Comment by SergK** [comment]
@ssmiller25, those CRs are part of the official Tekton interceptor installation payload:

 https://storage.googleapis.com/tekton-releases/triggers/previous/v0.25.3/interceptors.yaml

Here is how they are provisioned now:
https://github.com/civo/kubernetes-marketplace/blob/master/tekton/app.yaml#L5286

**Comment by saiyam1814** [comment]
I will approve sorry for the  delay

**Review by saiyam1814 — APPROVED** [review]

**Pull request merged**
