### PR TITLE
feat: Add KubeRocketCI platform to the CI/CD Stack

### PR DESCRIPTION
**Pull request by SergK**
We've changed the brand from the EPAM Delivery Platform (EDP) to the KubeRocketCI. And this is the first step on our migration path. The EDP will be removed in the next PRs

Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?
* [x] Have you included the specific version of the application to be installed?

If your pull request concerns an existing Marketplace application, please make sure you have:

* [ ] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [ ] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [ ] Tested that the application works with the proposed updates applied (including a screenshot).
* [ ] Updated the version number of the app if that has changed.

### CODE REVIEW

**Comment by SergK** [comment]
Hello, @kunal-kushwaha @civo-claire, any chance for review and merge? Thank you

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
Please include a screenshot in the comments after testing your application on the Civo managed Kubernetes service.

**Comment by SergK** [comment]
@kunal-kushwaha here is how I checked:

Create Job:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: install-kuberocketci
  namespace: default
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  manualSelector: false
  template:
    spec:
      containers:
        - name: install-kuberocketci-demo
          image: gcr.io/consummate-yew-302509/marketplace-installer:latest
          args:
            - install
            - kuberocketci
            - '-d'
            - https://github.com/SergK/kubernetes-marketplace.git
          env:
            - name: GITPROVIDER
              value: github
            - name: CLUSTER_ID
              value: 11d73884-0482-4364-9cfa-b6a74a5e7562
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  ttlSecondsAfterFinished: 172800
  completionMode: NonIndexed
  suspend: false
  podReplacementPolicy: TerminatingOrFailed
```

Check the results of the installer job (I've use repo from pull request):

```
{"time":"2024-07-02T13:50:57.225655312Z","level":"INFO","msg":"Cloneing git repo https://github.com/SergK/kubernetes-marketplace.git\n"}
{"time":"2024-07-02T13:50:57.225936479Z","level":"INFO","msg":"Creating temp dir to clone git repo"}
{"time":"2024-07-02T13:50:57.226185834Z","level":"INFO","msg":"Created temp dir: /tmp/prefix1235398467"}
{"time":"2024-07-02T13:50:58.527034416Z","level":"INFO","msg":"Validating that app exists: kuberocketci\n"}
{"time":"2024-07-02T13:50:58.527106429Z","level":"INFO","msg":"Running App PreInstall"}
{"time":"2024-07-02T13:50:58.52714973Z","level":"INFO","msg":"Cheking the pre_install.sh is preset or not"}
{"time":"2024-07-02T13:50:58.527198971Z","level":"INFO","msg":"No pre_install.sh found fo kuberocketci"}
{"time":"2024-07-02T13:50:58.527209019Z","level":"INFO","msg":""}
{"time":"2024-07-02T13:50:58.527216717Z","level":"INFO","msg":"Running App Install"}
{"time":"2024-07-02T13:50:58.528143507Z","level":"INFO","msg":"Cheking the install.sh is preset or not"}
{"time":"2024-07-02T13:50:58.528179717Z","level":"INFO","msg":"Running the install.sh"}
{"time":"2024-07-02T13:50:58.528202975Z","level":"INFO","msg":"Making the shell file executable"}
{"time":"2024-07-02T13:50:58.532646279Z","level":"INFO","msg":"Command output","stdout":""}
{"time":"2024-07-02T13:50:58.532716075Z","level":"ERROR","msg":"Command output","stderr":""}
{"time":"2024-07-02T13:50:58.532728878Z","level":"INFO","msg":"Running the shell file"}
{"time":"2024-07-02T13:50:58.532811143Z","level":"INFO","msg":"Shell file contents","shellFile":"OMIT-HERE=="}
{"time":"2024-07-02T13:51:15.28938529Z","level":"INFO","msg":"Command output","stdout":"\"epamedp\" has been added to your repositories\nHang tight while we grab the latest from your chart repositories...\n...Successfully got an update from the \"epamedp\" chart repository\nUpdate Complete. ⎈Happy Helming!⎈\ndeployment.apps/tekton-pipelines-webhook condition met\nclusterinterceptor.triggers.tekton.dev/cel unchanged\nclusterinterceptor.triggers.tekton.dev/github unchanged\nclusterinterceptor.triggers.tekton.dev/gitlab unchanged\nnamespace/edp created\nNAME: edp\nLAST DEPLOYED: Tue Jul  2 13:51:00 2024\nNAMESPACE: edp\nSTATUS: deployed\nREVISION: 1\nTEST SUITE: None\n"}
{"time":"2024-07-02T13:51:15.289548932Z","level":"ERROR","msg":"Command output","stderr":""}
{"time":"2024-07-02T13:51:15.289617382Z","level":"INFO","msg":"\"epamedp\" has been added to your repositories\nHang tight while we grab the latest from your chart repositories...\n...Successfully got an update from the \"epamedp\" chart repository\nUpdate Complete. ⎈Happy Helming!⎈\ndeployment.apps/tekton-pipelines-webhook condition met\nclusterinterceptor.triggers.tekton.dev/cel unchanged\nclusterinterceptor.triggers.tekton.dev/github unchanged\nclusterinterceptor.triggers.tekton.dev/gitlab unchanged\nnamespace/edp created\nNAME: edp\nLAST DEPLOYED: Tue Jul  2 13:51:00 2024\nNAMESPACE: edp\nSTATUS: deployed\nREVISION: 1\nTEST SUITE: None\n"}
```

image

**Review by kunal-kushwaha — APPROVED** [review]
lgtm

**Pull request merged**
