### PR TITLE
Added dynamic-pv-scaler to list

### PR DESCRIPTION
**Pull request by iamabhishek-dubey**
Signed-off-by: iamabhishek-dubey <abhishekbhardwaj510@gmail.com>

Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [X] Have you followed the guidelines in our Contributing document in setting up the application?
* [X] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [X] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [X] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

### CODE REVIEW

**Comment by iamabhishek-dubey** [comment]
image

**Comment by saiyam1814** [comment]
Can you define the benefits for the community for having this? Also, Is the repository actively maintained ? @iamabhishek-dubey

**Comment by iamabhishek-dubey** [comment]
Hey @saiyam1814 

So this resizes the persistent volumes by capturing the metrics from Prometheus and thresholds are configurable. And yes we do have some plans for this project like scaling on the basis of predictive analysis. annotations use instead of the config file.

**Comment by saiyam1814** [comment]
So it has a dependency on Prometheus, we need to have a check for that as well.

**Comment by iamabhishek-dubey** [comment]
Sure, but do you want me to add it inside `app.yaml` but that doesn't make sense because most of the time people will have their own Prometheus. Or is there any dependency section that can be added?

**Comment by saiyam1814** [comment]
No, I would not suggest having it inside app.yaml, instead, we need to check if Prometheus is already installed. Currently, in civo market place Prometheus operator is there, so we would be needing a few checks.

**Comment by iamabhishek-dubey** [comment]
Cool, please let me know what changes I can make at my end.

**Comment by saiyam1814** [comment]
Yes change the manifest and add dependencies of prometheus application 
refer here - https://github.com/civo/kubernetes-marketplace

**Comment by saiyam1814** [comment]
@iamabhishek-dubey can you add the dependency?

**Comment by iamabhishek-dubey** [comment]
@saiyam1814 I have added the dependency, please check

**Comment by saiyam1814** [comment]
I am testing this

**Comment by iamabhishek-dubey** [comment]
Sure

**Comment by saiyam1814** [comment]
@iamabhishek-dubey Can you ping me on civo slack have a couple of questions

**Comment by saiyam1814** [comment]
lgtm

**Pull request merged**
