### PR TITLE
RabbitMQ 

### PR DESCRIPTION
**Pull request by habil**
* [ X ] Have you followed the guidelines in our Contributing document in setting up the application?
* [ X ] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [ X ] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
  Screenshot: https://imgur.com/gixn66C
* [ X ] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

### CODE REVIEW

**Comment by saiyam1814** [comment]
Have you tested this on a civo created cluster? @habil

**Comment by habil** [comment]
Hello, @saiyam1814 Yes i have tested. Actually it is still working  on this url. http://rabbit.hcloud.tech/

**Comment by saiyam1814** [comment]
Awesome, Thank you for the PR, would you like to write a short writeup on how have you used RabbitMq with civo cloud? We can help you get that published as well. 
for the PR merge - @andyjeffries

**Comment by habil** [comment]
I will try to write as soon as possible.  Thank you also for your cooperation.

**Comment by saiyam1814** [comment]
LGTM

**Pull request merged**
