### PR TITLE
Update contributing guide, add PR and Issue templates

### PR DESCRIPTION
**Pull request by kaihoffman**

### CODE REVIEW

**Comment by kaihoffman** [comment]
Closes #20

**Comment by alexellis** [comment]
@kaihoffman inletsctl needs a change to its provisioning code here https://github.com/inlets/inletsctl/blob/master/pkg/civo.go#L159 to coincide with the merge / release of this fix where the endpoint returns 202 accepted instead of 200 ok.

**Comment by kaihoffman** [comment]
@alexellis I got this alert but can’t see the context on GitHub?
 
 

Kai Hoffman
Developer Advocate, Civo Ltd
Unit H-K, Gateway 1000, Whittle Way
Stevenage, Herts, SG1 2FP, UK
Visit us at www.civo.com <https://www.civo.com/>	 	Sign up for an account now > <https://www.civo.com/signup>

**Comment by andyjeffries** [comment]
This was a mistake - Alex was commenting in relation to a different thread. The documentation has been corrected over changing the endpoint responses.



Andy Jeffries FBCS CITP
Chartered Fellow of the British Computer Society
Taekwondo 7th Dan Master Instructor and Dan Grade Examiner
andyjeffries.co.uk @andyjeffries fb.com/andyjeffries

**Pull request merged**
