### PR TITLE
adding paralus to civo marketplace

### PR DESCRIPTION
**Pull request by niravparikh05**
Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [ ] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?
* [ ] Have you included the specific version of the application to be installed?

If your pull request concerns an existing Marketplace application, please make sure you have:

* [ ] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [ ] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [ ] Tested that the application works with the proposed updates applied (including a screenshot).
* [ ] Updated the version number of the app if that has changed.

### CODE REVIEW

**Comment by niravparikh05** [comment]
Fixes https://github.com/civo/kubernetes-marketplace/pull/469

**Comment by saiyam1814** [comment]
Hi @niravparikh05 Any updates on this ?

**Comment by niravparikh05** [comment]
@saiyam1814 let me try and confirm

**Comment by saiyam1814** [comment]
> @saiyam1814 let me try and confirm

Hey were you able to try this our ? screenshots would be helpful

**Comment by nirav-rafay** [comment]
@saiyam1814 yeah I am facing issues with contour ingress controller envoy pod which does not get scheduled with error `0/3 nodes are available: 1 node(s) didn't have free ports for the requested pod ports. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod.`

need to instruct contour to use civo lb, figuring it out how to do since there is not much documentation around it. Is this something you can help with ?

**Comment by niravparikh05** [comment]
@saiyam1814 yeah I am facing issues with contour ingress controller envoy pod which does not get scheduled with error 0/3 nodes are available: 1 node(s) didn't have free ports for the requested pod ports. preemption: 0/3 nodes are available: 3 No preemption victims found for incoming pod.

need to instruct contour to use civo lb, figuring it out how to do since there is not much documentation around it. Is this something you can help with ?

**Comment by niravparikh05** [comment]
thanks @saiyam1814 after disabling the default traefik ingress, I was able to successfully install paralus and test it out.

[here's the document](https://docs.google.com/document/d/1r4U5ntiHDa0do5eAraIhCPG1TzPavu9UbpJrQ_UMBaE/edit?usp=sharing) for your reference.

**Comment by saiyam1814** [comment]
I am merging this, please check the working also would be good to add https - I think you are using the clusterIP DNS which is not the DNS for contour. 
Ideal way would be to use palarus.Counter_LB_DNS and then setup using that. 
Maybe install contour, make a sleep of 30 seconds to get it ready and then fetch the DNS of LB and then use that to setup Palarus ?

**Comment by niravparikh05** [comment]
yeah that would work too as long as we are configuring our website DNS settings to redirect traffic to the configured cluster ingress.

**Review by saiyam1814 — APPROVED** [review]
Approving for further testing, will announce once fully tested.

**Pull request merged**
