### PR TITLE
WordPress updated to v5.6

### PR DESCRIPTION
**Pull request by javicv**
* WordPress updated to v5.6

---
* [x] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [x] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [x] Tested that the application works with the proposed updates applied (including a screenshot)

### CODE REVIEW

**Comment by saiyam1814** [comment]
Thank you for keeping this updated!

**Comment by DoNnMyTh** [comment]
@saiyam1814 this PR leaves manifest.yaml  for WP on 5.5.3

**Comment by javicv** [comment]
> @saiyam1814 this PR leaves manifest.yaml for WP on 5.5.3

My bad, I'll change it ASAP. Sorry.

**Comment by DoNnMyTh** [comment]
@javicv are you ok with #157

**Comment by javicv** [comment]
Looks good to me. Thanks

**Pull request merged**
