### PR TITLE
Updating Linkerd matketplace items to reflect the changes in 2.10

### PR DESCRIPTION
**Pull request by JasonMorgan**
Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

If your pull request concerns an existing Marketplace application, please make sure you have:

* [x] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [ ] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [x] Tested that the application works with the proposed updates applied (including a screenshot)

### CODE REVIEW

**Comment by JasonMorgan** [comment]
Hey folks! I've tested the changes in a civo cluster by running the various install scripts. Happy to provide screenshots but not sure what exactly I should capture. Would the `linkerd check` results work?

**Comment by JasonMorgan** [comment]
Also with regards to outlining my changes I'm not sure where the best place to do that is. I'm happy to write something up here in the comments or submit a doc somewhere if we have a more formal process.

**Comment by saiyam1814** [comment]
Yes Linkerd checks should work! 
What is the minimum cluster size required to run Linkerd ? Can we mention that in the post_install ? 
I will merge for now

**Comment by JasonMorgan** [comment]
image

Status checks on a 1 node cluster with Linkerd, linkerd-viz, and linkerd-jaeger installed.

extra small was too small and viz crashed Kubernetes on a 1 node.

**Pull request merged**
