### PR TITLE
Adding Falco-Security

### PR DESCRIPTION
**Pull request by DoNnMyTh**
Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

image

### CODE REVIEW

**Comment by saiyam1814** [comment]
Hello @DoNnMyTh Thank you for the PR , but currently, we  only support heml3 installs via yaml fille and not install.sh
The next version of the marketplace will be having this feature.

**Comment by DoNnMyTh** [comment]
@saiyam1814 so leave it open till then or should I close it ?

**Comment by saiyam1814** [comment]
Close this for now

**Comment by DoNnMyTh** [comment]
Sure

**Comment by DoNnMyTh** [comment]
Reopening

**Pull request closed without merging**
