### PR TITLE
add kubenav management application

### PR DESCRIPTION
**Pull request by si458**
Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

If your pull request concerns an existing Marketplace application, please make sure you have:

* [ ] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [ ] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [ ] Tested that the application works with the proposed updates applied (including a screenshot)

### CODE REVIEW

**Comment by saiyam1814** [comment]
Hi @si458 is this using helm3 ?

**Comment by si458** [comment]
Hi @saiyam1814
yes it is helm 3

**Comment by saiyam1814** [comment]
Currently, helm 3 is not supported directly , though you can create a yaml file as helm3 is supported in k3s. 
refer this - https://rancher.com/docs/k3s/latest/en/helm/

**Comment by si458** [comment]
Ah right ok no worries, will try with helm 2 and see what happens or change PR

**Comment by andyjeffries** [comment]
I would say got for helm 3 cattle yaml. Much cleaner solution. Helm 2 is deprecated

**Comment by saiyam1814** [comment]
I echo what Andy is saying

**Comment by si458** [comment]
@andyjeffries @saiyam1814 i cant get the helm 3 cattle yaml to work with a custom helm repo
i have however created a PR for a standard yaml file to be made publicly so we can just `kubectl create -f kubenav.yaml` 
https://github.com/kubenav/deploy/pull/5

**Comment by si458** [comment]
@andyjeffries @saiyam1814 ok managed to get it to work, a bit of googling and learning was required hehe
have updated the PR 👍

**Comment by saiyam1814** [comment]
Can you include a post_install.md file that just includes what and how to access and use kubenav? @si458

**Comment by si458** [comment]
@saiyam1814 done added one :)

**Comment by saiyam1814** [comment]
lgtm

**Comment by si458** [comment]
glad i could help, how long before its listed in the marketplace on the portal?

**Comment by saiyam1814** [comment]
It's in production

**Pull request merged**
