### PR TITLE
update maintainer cert-manager

### PR DESCRIPTION
**Pull request by NerdyShawn**
Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [X] Have you followed the guidelines in our Contributing document in setting up the application?
* [X] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [X] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot. **N/A Just maintainer updates, no manifest changes**
* [X] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?
* [X] Have you included the specific version of the application to be installed? **Mostly maintainer updates, no versions being touched**

If your pull request concerns an existing Marketplace application, please make sure you have:

* [ ] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [X] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [X] Tested that the application works with the proposed updates applied (including a screenshot).
* [X] Updated the version number of the app if that has changed.

### CODE REVIEW

**Comment by NerdyShawn** [comment]
Let me know if the maintainer tag makes sense or if there is another preferred. I believe I saw a few variations, github, email, etc. so just wanted to make sure it was consistent.
cc: @kunal-kushwaha

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
Why is the maintainer changed? Also can you please resolve the merge conflicts?

**Comment by NerdyShawn** [comment]
Merge conflicts resolved. The maintainer was updated per request of original uploader, more detail available on this issue here.
- https://github.com/civo/kubernetes-marketplace/issues/490#issuecomment-1719146738

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
Can you please fix the inconsistency in maintainer field?

**Review by kunal-kushwaha — APPROVED** [review]
Thank you!

**Pull request merged**
