### PR TITLE
Add Flagsmith to the marketplace

### PR DESCRIPTION
**Pull request by dabeeeenster**
Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [X] Have you followed the guidelines in our Contributing document in setting up the application?
* [X] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?
* [x] Have you included the specific version of the application to be installed?

If your pull request concerns an existing Marketplace application, please make sure you have:

* [ ] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [ ] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [ ] Tested that the application works with the proposed updates applied (including a screenshot).
* [ ] Updated the version number of the app if that has changed.

### CODE REVIEW

**Comment by dabeeeenster** [comment]
cc @kunal-kushwaha !

**Comment by kunal-kushwaha** [comment]
Thanks Ben! Lemme check

**Comment by dabeeeenster** [comment]
Any update here?

**Comment by kunal-kushwaha** [comment]
@dabeeeenster for point 3 can you please add the screenshot in the comments?

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
screenshot needed

**Comment by kunal-kushwaha** [comment]
@utkarsh-1905 do you have the screenshot of testing the application on Civo managed Kubernetes service?

**Review by kunal-kushwaha — APPROVED** [review]
lgtm

**Comment by kunal-kushwaha** [comment]
@dabeeeenster I believe I got this error internally. Can you please make another PR to fix this:

flagsmith/logo.png is wider than 512px
flagsmith/logo.png is taller than 512px
flagsmith/logo.png is larger than 20KB

**Comment by dabeeeenster** [comment]
OK this is added here https://github.com/civo/kubernetes-marketplace/compare/master...dabeeeenster:kubernetes-marketplace:master - should I reopen this PR?

**Pull request merged**
