### PR TITLE
Add Flux

### PR DESCRIPTION
**Pull request by stefanprodan**
This PR adds [Flux](https://github.com/fluxcd/flux2) to the marketplace using the [dev install mode](https://toolkit.fluxcd.io/guides/installation/#dev-install).

### CODE REVIEW

**Comment by saiyam1814** [comment]
Hi @stefanprodan good to see you raising the PR ,  can we have uninstall.sh as well for removing all components that gets installed in install.sh

**Comment by stefanprodan** [comment]
@saiyam1814 I used Linkerd as a template, didn't had `uninstall.sh`, I'll add it now.

**Comment by saiyam1814** [comment]
Thank you for pointing out I will raise an issue for that with Linkerd team :)

**Review by DoNnMyTh — APPROVED** [review]
Looks good to me just uninstall.sh is missing

**Comment by stefanprodan** [comment]
I've created a cluster to test this out, but the container images download is stuck:

```
$ ./flux/install.sh 
[INFO]  Downloading metadata https://api.github.com/repos/fluxcd/flux2/releases/latest
[INFO]  Using 0.12.3 as release
[INFO]  Downloading hash https://github.com/fluxcd/flux2/releases/download/v0.12.3/flux_0.12.3_checksums.txt
[INFO]  Downloading binary https://github.com/fluxcd/flux2/releases/download/v0.12.3/flux_0.12.3_darwin_amd64.tar.gz
[INFO]  Verifying binary download
[INFO]  Installing flux to /Users/stefanprodan/.flux/bin/flux
► checking prerequisites
✗ flux 0.12.1 <0.12.3 (new version is available, please upgrade)
✔ kubectl 1.21.0 >=1.18.0-0
✔ Kubernetes 1.20.2+k3s1 >=1.16.0-0
✔ prerequisites checks passed
✚ generating manifests
✔ manifests build completed
► installing components in flux-system namespace
◎ verifying installation
✗ source-controller: deployment not ready
✗ kustomize-controller: deployment not ready
✗ helm-controller: deployment not ready
✗ notification-controller: deployment not ready
✗ install failed
```

```
$ k -n flux-system get po
NAME                                      READY   STATUS    RESTARTS   AGE
helm-controller-5bbd94c75-ttl9x           0/1     Pending   0          8m57s
notification-controller-d66bdc787-dtcrx   0/1     Pending   0          8m56s
source-controller-86d84856cf-lslvg        1/1     Running   0          8m56s
kustomize-controller-97dbdcb99-pmp6r      1/1     Running   0          8m57s
```

```
k -n flux-system describe po helm-controller-5bbd94c75-ttl9x
Name:           helm-controller-5bbd94c75-ttl9x
Namespace:      flux-system
Priority:       0
Node:           k3s-flux-test-78a61e82-node-1bb7/
Labels:         app=helm-controller
                pod-template-hash=5bbd94c75
Annotations:    prometheus.io/port: 8080
                prometheus.io/scrape: true
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/helm-controller-5bbd94c75
Containers:
  manager:
    Image:       ghcr.io/fluxcd/helm-controller:v0.9.0
    Ports:       9440/TCP, 8080/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      --events-addr=http://notification-controller/
      --watch-all-namespaces=true
      --log-level=info
      --log-encoding=json
      --enable-leader-election
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   64Mi
    Liveness:   http-get http://:healthz/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:healthz/readyz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      RUNTIME_NAMESPACE:  flux-system (v1:metadata.namespace)
    Mounts:
      /tmp from temp (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from helm-controller-token-xm4gq (ro)
Conditions:
  Type           Status
  PodScheduled   True 
Volumes:
  temp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  helm-controller-token-xm4gq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  helm-controller-token-xm4gq
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  9m46s  default-scheduler  Successfully assigned flux-system/helm-controller-5bbd94c75-ttl9x to k3s-flux-test-78a61e82-node-1bb7
```

**Comment by stefanprodan** [comment]
After 15 minutes the container images from GHCR have been downloaded:

```
$ k -n flux-system get po
NAME                                      READY   STATUS    RESTARTS   AGE
source-controller-86d84856cf-lslvg        1/1     Running   0          16m
kustomize-controller-97dbdcb99-pmp6r      1/1     Running   0          16m
helm-controller-5bbd94c75-ttl9x           1/1     Running   0          16m
notification-controller-d66bdc787-dtcrx   1/1     Running   0          16m
```

**Comment by stefanprodan** [comment]
Flux is working fine after the images got downloaded:

```
kubernetes-marketplace $ flux create source git podinfo --url https://github.com/stefanprodan/podinfo
✚ generating GitRepository source
► applying GitRepository source
✔ GitRepository source created
◎ waiting for GitRepository source reconciliation
✔ GitRepository source reconciliation completed
✔ fetched revision: master/ef98a040c89180a4f39c0ab01dac47e6c3fced08
kubernetes-marketplace $ flux create kustomization podinfo --source podinfo --path kustomize --prune 
✚ generating Kustomization
► applying Kustomization
✔ Kustomization created
◎ waiting for Kustomization reconciliation
✔ Kustomization podinfo is ready
✔ applied revision master/ef98a040c89180a4f39c0ab01dac47e6c3fced08
```

**Comment by saiyam1814** [comment]
Thanks Stefan, the team has been notified about the issue and will be looking into this. PR looks good to me and I will merge it

**Comment by ChipWolf** [comment]
Has anyone who uses Flux made use of this app? I don't think we've fully captured the use case with this change at all.

`flux bootstrap` still must be run following the install of this app from the marketplace. The bootstrap process for Flux normally installs the stack, so this app is completely redundant without the bootstrap process being included in the app's installation.

I imagined the Flux integration for Civo would effectively make a cluster zero-touch. A field should be exposed in the UI for this app so you can specify a git repo along with an SSH private key for Flux to bootstrap with.

**Comment by saiyam1814** [comment]
the user input while installing the app is not there, I would request you to put that in the suggestions area in your Civo account and we can open it for voting and then implement it as a feature that can help cater this use-case

**Comment by stefanprodan** [comment]
As stated in the PR description, this one-click deploy is for dev/test clusters only. I don't expect people to use this for production, instead you should use `flux bootstrap` as documented here: https://toolkit.fluxcd.io/guides/installation/

Having a UI where you would paste your Git token sounds really dangerous to me, if Civo stores the token in their logs then this could be a major security risk. Imagine that someone gets hold of those logs and then it can access your Git repos, delete them, push code, etc. In the end is about trust, the flux CLI runs on your own machine, if you run the CLI on someone else's computer aka the cloud, then you must trust the vendor that it can keep your secrets safe.

**Comment by ChipWolf** [comment]
Outside of this specific use case; I strongly believe a feature for user-defined variables and secrets would reduce the friction of setting up a cluster and could expand the available use-cases.

If I'm trusting Civo with the data in my clusters and the secrets stored in the cluster, a few variables in addition to that for the setup flow is not a massive deal, especially if it reduces the time to go-live.

> Having a UI where you would paste your Git token sounds really dangerous to me, if Civo stores the token in their logs then this could be a major security risk.

I'd say the same goes for everything, from password and payment fields to the Kubernetes tokens required to interact with the cluster. I don't doubt Civo can handle some additional secret material if it results in better UX.

**Pull request merged**
