### PR TITLE
Adding Polaris tool

### PR DESCRIPTION
**Pull request by milindchawre**
Adding Polaris tool to civo marketplace.
Tool category is security.

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

**Screenshot**
image

### CODE REVIEW

**Comment by saiyam1814** [comment]
@milindchawre polaris/logo.png isn't a square aspect ratio image, can ou fix that?

**Comment by milindchawre** [comment]
@andyjeffries  @saiyam1814  Unfortunately I can only find official logo [here](https://github.com/FairwindsOps/polaris/blob/master/img/polaris-logo.png) whose aspect ratio, dimension and size is not appropriate. I tried to resize the dimension keeping the aspect ratio. But changing to square shape will mess up the aspect ratio and the image will look either stretched out or narrowed. What you suggest?

**Comment by andyjeffries** [comment]
polaris

What we normally do is pad it with transparent pixels to be square. I found a nice SVG of their logo on their site and made one for you. Please update the PR with this and I'll get it merged.

**Comment by milindchawre** [comment]
@andyjeffries  Done! Can you also point out how you got the SVG version, might come handy next time.

**Comment by andyjeffries** [comment]
I literally went to https://www.fairwinds.com/open-source-software, scrolled down to Polaris and dragged the image to my desktop - found it was a nice scalable SVG :-)

**Comment by milindchawre** [comment]
ohh I see thanks.

**Pull request merged**
