### PR TITLE
Uplated wordpress joomla mongodb nextcloud

### PR DESCRIPTION
**Pull request by DoNnMyTh**
Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

This Pull request is for updating Wordpress, joomla, nextcloud and mongodb:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?

### CODE REVIEW

**Comment by saiyam1814** [comment]
@keithhubner are you ok with the changes ?

**Review by keithhubner — COMMENTED** [review]
Seem OK to me.

**Comment by javicv** [comment]
@DoNnMyTh wordpress manifest seems good to me.

Could you also modify nodered/manifest.yaml to match manifest version (1.2.3) with app.yaml (1.2.7), I forgot that in #144 :disappointed:

**Review by javicv — APPROVED** [review]

**Comment by saiyam1814** [comment]
@DoNnMyTh this branch has conflicts can you rework ?

**Comment by DoNnMyTh** [comment]
rework ? no its only for wordpress joomla mongo and nextcloud

**Comment by DoNnMyTh** [comment]
> 
> 
> @DoNnMyTh wordpress manifest seems good to me.
> 
> Could you also modify nodered/manifest.yaml to match manifest version (1.2.3) with app.yaml (1.2.7), I forgot that in #144 😞

#163 is created to fix this issue

**Pull request merged**
