### PR TITLE
Added Bitwarden Passwordless.dev app to marketplace

### PR DESCRIPTION
**Pull request by keithhubner**
Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [ X] Have you followed the guidelines in our Contributing document in setting up the application?
* [X ] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [ X] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* 
Screenshot 2024-06-11 at 06 23 23
Screenshot 2024-06-11 at 06 23 34

* [X ] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?
* [X ] Have you included the specific version of the application to be installed?

If your pull request concerns an existing Marketplace application, please make sure you have:

* [ ] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [ ] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [ ] Tested that the application works with the proposed updates applied (including a screenshot).
* [ ] Updated the version number of the app if that has changed.

### CODE REVIEW

**Comment by saiyam1814** [comment]
@keithhubner the pre_install is not working currently @vishalanarase is working on the fix. TIll that if can find any other alternative, I would be happy to merge. Till then even if I merge, it wont work.

**Comment by kunal-kushwaha** [comment]
@vishalanarase do you have any updates on the fix?

**Comment by vishalanarase** [comment]
@kunal-kushwaha  It's been merged and existing apps with `pre_install.sh` are working.

**Comment by keithhubner** [comment]
Is this in the marketplace yet?

**Comment by vishalanarase** [comment]
> Is this in the marketplace yet?

No, did you tested this app in the civo-kubernetes cluster?

**Comment by keithhubner** [comment]
@kunal-kushwaha it is a seperate product. This is for self hosting the passwordless.dev product.

**Review by kunal-kushwaha — CHANGES_REQUESTED** [review]
For point 3, can you please include the screenshot?

**Comment by keithhubner** [comment]
Yeah, i'll need to deploy it fresh tomorrow, then will include. Cheers

**Comment by keithhubner** [comment]
Screenshot uploaded

**Review by kunal-kushwaha — APPROVED** [review]
lgtm

**Pull request merged**
