### PR TITLE
Update issue_template.md

### PR DESCRIPTION
**Pull request by si458**
fix checkboxs

Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

If your pull request concerns an existing Marketplace application, please make sure you have:

* [x] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [x] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [x] Tested that the application works with the proposed updates applied (including a screenshot)

### CODE REVIEW

**Comment by saiyam1814** [comment]
@kaihoffman ^^

**Comment by kaihoffman** [comment]
@si458 sorry for the delay here - I can't see a difference in how the checkboxes render with the existing markdown and your proposed change. Are you able to let me know if there's a functional difference?

**Comment by si458** [comment]
@kaihoffman forgive my delay too

currently the template just creates two square brackets with nothing inside so the end user has to put something inside them to show which option they mean

Where as this PR changes them to physical checkboxes for the end user to just tick which option they want instead 😀

**Comment by saiyam1814** [comment]
@kaihoffman is it good to merge ?

**Comment by kaihoffman** [comment]
Sure, I didn't know it hadn't been! @saiyam1814

**Comment by saiyam1814** [comment]
Thanks, Merging

**Pull request merged**
