### PR TITLE
Update Gitea to latest chart version (2.1.6)

### PR DESCRIPTION
**Pull request by techknowlogick**
This includes an upgrade to latest chart version which also includes upgrade to latest stable Gitea version (which includes security fixes)

If your pull request concerns an existing Marketplace application, please make sure you have:

* [x] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [x] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [x] Tested that the application works with the proposed updates applied (including a screenshot)

### CODE REVIEW

**Comment by saiyam1814** [comment]
Is it good to be merged or some more work needed?

**Comment by saiyam1814** [comment]
@techknowlogick is it still WIP or good to merge?

**Comment by techknowlogick** [comment]
Thanks for ping @saiyam1814, the helm chart has received several updates recently and so the testing that I had done for this PR now needs to be redone, apologies for delay

**Comment by saiyam1814** [comment]
No Problem

**Comment by techknowlogick** [comment]
@saiyam1814 no longer WIP

**Comment by saiyam1814** [comment]
Thanks @techknowlogick , Will merge it once our new platform is out.

**Comment by saiyam1814** [comment]
Merging , thanks for keeping it up to date!

**Pull request merged**
