### PR TITLE
create namespace in helm via flag

### PR DESCRIPTION
**Pull request by dscamargo**
My proposal is change kubectl create namespace command to add flag in helm command `--create-namespace` to code be more readable.

Screen Shot 2021-08-12 at 4 05 19 PM

### CODE REVIEW

**Comment by dscamargo** [comment]
ping @saiyam1814

**Comment by saiyam1814** [comment]
ping @dirien what are your thoughts ?

**Comment by dirien** [comment]
In this case its fine, as we do not have some fancy stuff (resources management on NS level etc) going on with the namepace. So there is not real need to create it beforehand.  So -> /LGTM

**Comment by saiyam1814** [comment]
cool merging

**Pull request merged**
