### PR TITLE
Issue:#522 Updated version Reloader to new

### PR DESCRIPTION
**Pull request by Pushkarmondal**
* [x] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [x] Outlined the changes you are proposing, and the reasons these are required (e.g., stability, compatibility with new versions of Kubernetes implementations, etc).
* [x] Tested that the application works with the proposed updates applied (including a screenshot).
* [x] Updated the version number of the app if that has changed.

### CODE REVIEW

**Comment by dirien** [comment]
LGTM! thanks @Pushkarmondal for the work!

**Comment by Pushkarmondal** [comment]
Hey @dirien can you please check my pr.

**Comment by Pushkarmondal** [comment]
@dirien Then what next?

**Comment by dirien** [comment]
@Pushkarmondal maybe @alejandrojnm or @kaihoffman can give an answer?

**Comment by Pushkarmondal** [comment]
Hey @alejandrojnm @kaihoffman can you please look into this?

**Review by alejandrojnm — APPROVED** [review]

**Comment by kaihoffman** [comment]
I trust that this works given @alejandrojnm merged but @Pushkarmondal I didn't see a screenshot confirming the new version works?

**Comment by Pushkarmondal** [comment]
Ok I will attach.

**Pull request merged**
