### PR TITLE
Bump version for OpenFaaS

### PR DESCRIPTION
**Pull request by alexellis**
Updated the version and the blurb to match other marketplace
entries.

Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>

### CODE REVIEW

**Comment by alexellis** [comment]
@andyjeffries PTAL?

**Comment by andyjeffries** [comment]
Hi @alexellis, no idea what PTAL means?

Happy to have the version bump, but after a little internal discussion, we feel the new description is too salesy. Also while the new version was within the prescribed limits, when we put it in place locally on a test site it's just too long compared to the others, so we've decided to shorten the limit.

We've just updated the README with a better limit of 160 characters - yours is currently the longest out of all of them with 153 anyway. We want to think of it as the SMS description of your app. We've also clarified in the README that the descriptions aren't to be salesy. For example, to make your description fit the new requirements:

> OpenFaaS is an award-winning open source project that makes it easy for developers to deploy applications to Kubernetes in a Serverless-style. Any microservice, API, binary, or function can be packaged and deployed in a very short period of time.

To

> OpenFaaS is an open source Serverless deployment platform for Kubernetes. Any microservice, API, binary, or function can be packaged and deployed quickly.

**Comment by alexellis** [comment]
PTAL = Please Take A Look.

**Comment by alexellis** [comment]
I didn't know about the 160 char limit, this was pasted from our other marketplace entry, including the words "award-winning" is not "salesy" IMHO.

I'll send a follow-up PR that fits within your requirements, but let me come up with the wording please.

**Comment by andyjeffries** [comment]
Happy for you to come up with the revised wording, it was just an example :-)

**Comment by andyjeffries** [comment]
Happy with that wording. Merging now.

**Pull request merged**
