### PR TITLE
kubevious

### PR DESCRIPTION
**Pull request by saiyam1814**
Installing Kubevious to civo k3s cluster

### CODE REVIEW

**Comment by andyjeffries** [comment]
If by default it installs an ingress, how is it secured against anyone viewing it?

**Comment by saiyam1814** [comment]
Security Meaning?

**Comment by alejandrojnm** [comment]
Yes, after you create the ingress, how you prevent other people enter to the UI

**Comment by saiyam1814** [comment]
So it does not have the write Access I believe, you cannot create resources and only view them within the cluster 
I have it deployed here. You can check and try if you can do something with the cluster -  http://91.211.152.29:30078/

**Comment by saiyam1814** [comment]
Here is the blogpost for running it on CIVO cloud k3s cluster in general. 
https://saiyampathak.com/let-us-take-a-dig-into-kubevious-ckea9d9r700muxhs19jtr3xr8 
Published a few minutes back

**Comment by saiyam1814** [comment]
How about after we create it helm , we delete the Service Nodeport and create a cluster Ip service and then via portforward for access and not exposed only to the outside world forever?

**Comment by andyjeffries** [comment]
That sounds better. I just worry about someone getting access they shouldn't have. Even read only access may give away things you don't want giving away.

**Comment by saiyam1814** [comment]
That is true, I raised this with kubevious team they will be soon coming up with some auth mechanism. Also this PR is I believe based on helm3 should be fine or should I create the manifests?

**Comment by andyjeffries** [comment]
We don't install the helm v3 client on the nodes. So you can use k3s helm.cattle.io CRD with a v3 flag, or manifests. Either way works for us :-)

**Comment by saiyam1814** [comment]
gotcha so this won't work right? either I need the CRD or the manifests?

**Comment by andyjeffries** [comment]
I assumed it was a Helm 2 chart. So, no, it won't work then. Need to either use the CRD for Helm 3 or the manifests.

**Pull request merged**
