### PR TITLE
Adding Dapr to marketplace

### PR DESCRIPTION
**Pull request by salaboy**
Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?
* [x] Have you included the specific version of the application to be installed?

Screenshot 2024-01-04 at 08 44 32

If your pull request concerns an existing Marketplace application, please make sure you have:

* [ ] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [ ] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [ ] Tested that the application works with the proposed updates applied (including a screenshot).
* [ ] Updated the version number of the app if that has changed.

### CODE REVIEW

**Comment by salaboy** [comment]
Does this PR failed some CI task? Or is it just waiting for a review?

**Comment by salaboy** [comment]
Fixed CI issue

**Review by saiyam1814 — APPROVED** [review]
Thank you for the PR my friend, lgtm

**Comment by saiyam1814** [comment]
@salaboy got a CI error, can you fix the logo please ?
``` dapr/logo.png isn't a square aspect ratio image
```

**Comment by salaboy** [comment]
@saiyam1814 I've pushed the square logo to my branch.. can you check it from there?

**Comment by salaboy** [comment]
@saiyam1814 because this branch was merged already: https://github.com/salaboy/kubernetes-marketplace/blob/master/dapr/logo.png

**Pull request merged**
