### PR TITLE
install cert-manager version 1.0.2

### PR DESCRIPTION
**Pull request by rberrelleza**
fixes #14 

Update marketplace to the 1.0.2 version of cert-manager, now that they released a stable version.

Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

If your pull request concerns an existing Marketplace application, please make sure you have:

* [ ] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [x] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [x] Tested that the application works with the proposed updates applied (including a screenshot)

### CODE REVIEW

**Comment by saiyam1814** [comment]
lgtm

**Comment by javicv** [comment]
Doesn't this also fix #40 ?

**Comment by rberrelleza** [comment]
@javicv yes, but guides might need to be updated cc @saiyam1814

**Comment by saiyam1814** [comment]
@kaihoffman can you have a look at the guides and docs related to this ?

**Pull request merged**
