### PR TITLE
Add Gitea as app to CIVO marketplace

### PR DESCRIPTION
**Pull request by techknowlogick**
Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
Screen Shot 2020-10-07 at 3 06 09 PM
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

### CODE REVIEW

**Comment by andyjeffries** [comment]
Thanks for your first submission to the marketplace. Can I ask, what inspired you to create this PR today?

**Comment by techknowlogick** [comment]
> Can I ask, what inspired you to create this PR today?

I've been a part of KUBE100 for sometime now, and I am a project lead of Gitea where we just (a few weeks ago) launched our helm chart, so it was kismet. Plus when testing our helm chart I was using a CIVO k3s cluster to verify changes.

**Comment by andyjeffries** [comment]
I've added it to our marketplace now, our marketing team will tweet about it in the morning (it's nearly 9pm in the UK, so they've all gone home).

**Comment by techknowlogick** [comment]
> our marketing team will tweet about it in the morning 

awesome! I'll make sure to re-tweet :)

**Pull request merged**
