### PR TITLE
fix: Install Istio using Marketplace

### PR DESCRIPTION
**Pull request by kameshsampath**
fixes: 206

Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
image

istio_pr_post_install

istio_pr_uninstall

* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

### CODE REVIEW

**Comment by kameshsampath** [comment]
@saiyam1814 @DoNnMyTh  FYI

**Comment by DoNnMyTh** [comment]
I'll check it tomorrow 🙂

**Comment by DoNnMyTh** [comment]
@kameshsampath We need to have a call about this i'm seeing many issues, It needs some work before it can be merged. Ping me when you are free

**Review by DoNnMyTh — APPROVED** [review]
@saiyam1814 it can be merged 
image

**Comment by saiyam1814** [comment]
@kameshsampath we have a rule mentioned in the docs 
We envisage that install.sh script usage should be rare and we will be strictly monitoring what is in them, and NO downloading of external resources will be acceptable here (no curl https://... | sudo sh sort of functionality)


Now we have made this rule a little flexible for maintainer maintained apps only, this means if you are a maintainer of a project and you want to include that project in civo marketplace then you can make use of the cli based on mutual agreement. 
So if you are an istio maintainer, please verify or if we can get an istio maintainer as one of the maintainers then also fine.

**Comment by kameshsampath** [comment]
@saiyam1814  if you want to see the contents of the install script its just this https://raw.githubusercontent.com/istio/istio/master/release/downloadIstioCandidate.sh. I will try to see if I can I make download the tarball and unzip myself than via installer script. I hope that wil help ?

**Comment by kameshsampath** [comment]
@saiyam1814  - can you please take look at it now, I have moved out the `install.sh` script

**Comment by saiyam1814** [comment]
Thanks, @kameshsampath LGTM

**Comment by kameshsampath** [comment]
thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
