### PR TITLE
traefik2-loadbalancer: Upgrade to v2.11.1; resolves #734

### LINKED ISSUE #734: Upgrade Traefik from 2.9.4 to 2.11.1
This issue is a:
* [X] Bug Report
* [X] Enhancement suggestion
* [ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

johannes@jitesoft.com, saiyam@civo.com

## Enhancement suggestions / feature requests

Traefik 2.9.4 is absolutely ancient (2022) and doesn't support non-beta ingress specifications.

Traefik [2.11.1](https://github.com/traefik/traefik/releases/tag/v2.11.1) should be a lot more modern, while supporting both the legacy beta ingress as well as the stable ingress api.

(Traefik 3.x removes the legacy beta ingress, so may want to hold off on 3.x for now)

### PR DESCRIPTION
**Pull request by kallisti5**
* Correct spelling mistakes in post-install readme
* Add missing CRD definitions
* Sync roles to traefik 2.11 examples while keeping custom civo naming

Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

### CODE REVIEW

**Comment by kallisti5** [comment]
Tested functional on civo.  Traefik is the default ingress controller when applied.  v2.11.1 is just coming out, but doesn't have an official image yet so went with v2.11.0.

**Comment by kallisti5** [comment]
There's a few missing CRD definitions, but substantially better than what is offered now.

```
$ kubectl -n kube-system logs traefik-vvxww
time="2024-04-10T18:11:37Z" level=info msg="Configuration loaded from flags."
W0410 18:11:37.063061       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.TraefikService: the server could not find the requested resource (get traefikservices.traefik.containo.us)
E0410 18:11:37.063254       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.TraefikService: failed to list *v1alpha1.TraefikService: the server could not find the requested resource (get traefikservices.traefik.containo.us)
W0410 18:11:37.064272       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.TLSStore: the server could not find the requested resource (get tlsstores.traefik.containo.us)
E0410 18:11:37.064405       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.TLSStore: failed to list *v1alpha1.TLSStore: the server could not find the requested resource (get tlsstores.traefik.containo.us)
W0410 18:11:37.065140       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.ServersTransport: the server could not find the requested resource (get serverstransports.traefik.containo.us)
E0410 18:11:37.065266       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.ServersTransport: failed to list *v1alpha1.ServersTransport: the server could not find the requested resource (get serverstransports.traefik.containo.us)
W0410 18:11:37.067205       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha1.TLSOption: the server could not find the requested resource (get tlsoptions.traefik.containo.us)
E0410 18:11:37.067354       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha1.TLSOption: failed to list *v1alpha1.TLSOption: the server could not find the requested resource (get tlsoptions.traefik.containo.us)
```

**Comment by kallisti5** [comment]
Verification of functionality:
```
$ kubectl -n kube-system get pods | grep traefik
traefik-vvxww               1/1     Running            0                43m
traefik-klt5b               1/1     Running            0                43m
```

```
$ kubectl get ingress
NAME                 CLASS    HOSTS   ADDRESS         PORTS   AGE
terarocket-ingress   <none>   *       212.2.240.225   80      42m
```

```
$ curl http://212.2.240.225  -v 2>&1 > /dev/null | grep HTTP/1.1
> GET / HTTP/1.1
< HTTP/1.1 200 OK
```

**Comment by saiyam1814** [comment]
@aakashnagpal4567 can you test this PR for Kubernetes 1.27 talos, 1.28 k3s and 1.29 k3s?

**Comment by aakashnagpal4567** [comment]
> @aakashnagpal4567 can you test this PR for Kubernetes 1.27 talos, 1.28 k3s and 1.29 k3s?
will test this

**Comment by aakashnagpal4567** [comment]
@saiyam1814 I have tested this, and it's working fine for 1.27 Talos, 1.28 k3s and 1.29 k3s

**Comment by kallisti5** [comment]
I can look into upgrading traefik2-nodeport with similar changes next.   I mostly upgraded these because it makes using civo a lot easier :sweat_smile:.

I'd recommend bumping to 2.11.1 when it comes out, but that should be a pretty minor change since these cluster roles, CRD's etc should work for 2.11.x

**Comment by saiyam1814** [comment]
Thanks for the PR!

**Review by saiyam1814 — APPROVED** [review]
Approving as per testing by @aakashnagpal4567

**Pull request merged**
