### PR TITLE
Add Chaos Mesh

### PR DESCRIPTION
**Pull request by cwen0**
Signed-off-by: cwen0 <cwenyin0@gmail.com>

Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository!

If your pull request is to submit a new application to the marketplace, please answer the following questions:

* [x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?

### CODE REVIEW

**Comment by cwen0** [comment]
image

**Comment by saiyam1814** [comment]
@cwen0 error is 
```
chaos-mesh/logo.png isn't a square aspect ratio image

```

**Comment by saiyam1814** [comment]
Awesome its passed !!!

**Comment by saiyam1814** [comment]
@cwen0 the app is in production but after installing and opening the UI there is TOKEN required, can we have the POST install steps for getting the token and which one to use ?

**Pull request merged**
